name: Swift

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    strategy:
      matrix:
        os: [
            macos-15,
            # ubuntu-latest, # TODO: Enable this once Swift 6.0 is available on GitHub Actions. See https://github.com/swift-actions/setup-swift/issues/683
          ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Install Swift
        if: runner.os == 'Linux'
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0"
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
